# Generated by Django 6.0.4 on 2026-05-01 08:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=255)),
                ("picture", models.URLField(blank=True, default="")),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("whatsapp_optin", models.BooleanField(default=False)),
                (
                    "synced_providers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("category", models.CharField(default="Other", max_length=50)),
                ("date", models.DateField()),
                ("product_name", models.TextField(blank=True, default="")),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "mrp",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.user",
                        to_field="google_id",
                    ),
                ),
            ],
            options={
                "db_table": "expenses",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.user",
                        to_field="google_id",
                    ),
                ),
            ],
            options={
                "db_table": "push_subscriptions",
                "unique_together": {("user", "subscription")},
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=7)),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.user",
                        to_field="google_id",
                    ),
                ),
            ],
            options={
                "db_table": "budgets",
                "unique_together": {("user", "month")},
            },
        ),
    ]
