# Generated by Django 6.0.4 on 2026-05-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_hash",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
